v40-160-280/:
GenStudy_JetMtahed_RelaxedJet_FdataDATA_minChi2.root
GenStudy_JetMtahed_RelaxedJet_FdataMC_minChi2.root
GenStudy_JetMtahed_RelaxedJet_FmcMC_minChi2.root
Makefile
README
SignalStudy.C
StudyTheSignal

v50-150-280/:
GenStudy_JetMtahed_RelaxedJet_FdataDATA_minChi2.root
GenStudy_JetMtahed_RelaxedJet_FdataMC_minChi2.root
GenStudy_JetMtahed_RelaxedJet_FmcMC_minChi2.root
Makefile
README
SignalStudy.C
StudyTheSignal

v50-160-270/:
GenStudy_JetMtahed_RelaxedJet_FdataDATA_minChi2.root
GenStudy_JetMtahed_RelaxedJet_FdataMC_minChi2.root
GenStudy_JetMtahed_RelaxedJet_FmcMC_minChi2.root
Makefile
README
SignalStudy.C
StudyTheSignal

v50-160-290/:
GenStudy_JetMtahed_RelaxedJet_FdataDATA_minChi2.root
GenStudy_JetMtahed_RelaxedJet_FdataMC_minChi2.root
GenStudy_JetMtahed_RelaxedJet_FmcMC_minChi2.root
Makefile
README
SignalStudy.C
StudyTheSignal

v50-170-280/:
GenStudy_JetMtahed_RelaxedJet_FdataDATA_minChi2.root
GenStudy_JetMtahed_RelaxedJet_FdataMC_minChi2.root
GenStudy_JetMtahed_RelaxedJet_FmcMC_minChi2.root
Makefile
README
SignalStudy.C
StudyTheSignal

v60-160-280/:
GenStudy_JetMtahed_RelaxedJet_FdataDATA_minChi2.root
GenStudy_JetMtahed_RelaxedJet_FdataMC_minChi2.root
GenStudy_JetMtahed_RelaxedJet_FmcMC_minChi2.root
Makefile
README
SignalStudy.C
StudyTheSignal
