 cd JES-DOWN;  ../FitCominedJES signal8 ../nominal/TChannel_plots.root signal8 ../nominal/TbarChannel_plots.root signal8 ../nominal/SChannel_plots.root signal8 ../nominal/SbarChannel_plots.root signal8 ../nominal/TWChannel_plots.root signal8 ../nominal/TbarWChannel_plots.root signal8 ../nominal/TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_JES-down.root  signal7 mue_JES-down.root  signal7 muhad_JES-down.root  signal7 mutau_JES-down.root  signal7 others_JES-down.root  signal7 sbar_JES-down.root  signal7 s_JES-down.root  signal7 tbar_JES-down.root  signal7 t_JES-down.root  signal7 tWbar_JES-down.root  signal7 tW_JES-down.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root> corfit7.txt; cd -;

 cd UNCMET-DOWN;  ../FitCominedJES signal8 ../nominal/TChannel_plots.root signal8 ../nominal/TbarChannel_plots.root signal8 ../nominal/SChannel_plots.root signal8 ../nominal/SbarChannel_plots.root signal8 ../nominal/TWChannel_plots.root signal8 ../nominal/TbarWChannel_plots.root signal8 ../nominal/TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_MET-down.root  signal7 mue_MET-down.root  signal7 muhad_MET-down.root  signal7 mutau_MET-down.root  signal7 others_MET-down.root  signal7 sbar_MET-down.root  signal7 s_MET-down.root  signal7 tbar_MET-down.root  signal7 t_MET-down.root  signal7 tWbar_MET-down.root  signal7 tW_MET-down.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root > corfit7.txt; cd -;

 cd JES-UP;  ../FitCominedJES signal8 ../nominal/TChannel_plots.root signal8 ../nominal/TbarChannel_plots.root signal8 ../nominal/SChannel_plots.root signal8 ../nominal/SbarChannel_plots.root signal8 ../nominal/TWChannel_plots.root signal8 ../nominal/TbarWChannel_plots.root signal8 ../nominal/TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_JES-up.root  signal7 mue_JES-up.root  signal7 muhad_JES-up.root  signal7 mutau_JES-up.root  signal7 others_JES-up.root  signal7 sbar_JES-up.root  signal7 s_JES-up.root  signal7 tbar_JES-up.root  signal7 t_JES-up.root  signal7 tWbar_JES-up.root  signal7 tW_JES-up.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root> corfit7.txt; cd -;

cd UNCMET-UP;  ../FitCominedJES signal8 ../nominal/TChannel_plots.root signal8 ../nominal/TbarChannel_plots.root signal8 ../nominal/SChannel_plots.root signal8 ../nominal/SbarChannel_plots.root signal8 ../nominal/TWChannel_plots.root signal8 ../nominal/TbarWChannel_plots.root signal8 ../nominal/TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_MET-up.root  signal7 mue_MET-up.root  signal7 muhad_MET-up.root  signal7 mutau_MET-up.root  signal7 others_MET-up.root  signal7 sbar_MET-up.root  signal7 s_MET-up.root  signal7 tbar_MET-up.root  signal7 t_MET-up.root  signal7 tWbar_MET-up.root  signal7 tW_MET-up.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root> corfit7.txt; cd -;

cd lumi-DOWN;  ../FitComined signal8 ../nominal/TChannel_plots.root signal8 ../nominal/TbarChannel_plots.root signal8 ../nominal/SChannel_plots.root signal8 ../nominal/SbarChannel_plots.root signal8 ../nominal/TWChannel_plots.root signal8 ../nominal/TbarWChannel_plots.root signal8 ../nominal/dimu_TTBar_plots.root signal8 ../nominal/muTau_TTBar_plots.root signal8 ../nominal/muE_TTBar_plots.root signal8 ../nominal/muHad_TTBar_plots.root signal8 ../nominal/others_TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_lumi-down.root  signal7 mue_lumi-down.root  signal7 muhad_lumi-down.root  signal7 mutau_lumi-down.root  signal7 rest_lumi-down.root  signal7 sbar_lumi-down.root  signal7 s_lumi-down.root  signal7 tbar_lumi-down.root  signal7 t_lumi-down.root  signal7 tWbar_lumi-down.root  signal7 tW_lumi-down.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root> corfit7.txt; cd -;

cd lumi-UP;  ../FitComined signal8 ../nominal/TChannel_plots.root signal8 ../nominal/TbarChannel_plots.root signal8 ../nominal/SChannel_plots.root signal8 ../nominal/SbarChannel_plots.root signal8 ../nominal/TWChannel_plots.root signal8 ../nominal/TbarWChannel_plots.root signal8 ../nominal/dimu_TTBar_plots.root signal8 ../nominal/muTau_TTBar_plots.root signal8 ../nominal/muE_TTBar_plots.root signal8 ../nominal/muHad_TTBar_plots.root signal8 ../nominal/others_TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_lumi-up.root  signal7 mue_lumi-up.root  signal7 muhad_lumi-up.root  signal7 mutau_lumi-up.root  signal7 rest_lumi-up.root  signal7 sbar_lumi-up.root  signal7 s_lumi-up.root  signal7 tbar_lumi-up.root  signal7 t_lumi-up.root  signal7 tWbar_lumi-up.root  signal7 tW_lumi-up.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root> corfit7.txt; cd -;

