cd btag-DOWN;  ../FitComined signal8 TChannel_plots.root signal8 TbarChannel_plots.root signal8 SChannel_plots.root signal8 SbarChannel_plots.root signal8 TWChannel_plots.root signal8 TbarWChannel_plots.root signal8 dimu_TTBar_plots.root signal8 muTau_TTBar_plots.root signal8 muE_TTBar_plots.root signal8 muHad_TTBar_plots.root signal8 others_TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_btag-down.root  signal7 mue_btag-down.root  signal7 muhad_btag-down.root  signal7 mutau_btag-down.root  signal7 others_btag-down.root  signal7 sbar_btag-down.root  signal7 s_btag-down.root  signal7 tbar_btag-down.root  signal7 t_btag-down.root  signal7 tWbar_btag-down.root  signal7 tW_btag-down.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root > fit2.txt; cd -;

cd ctag-DOWN;  ../FitComined signal8 TChannel_plots.root signal8 TbarChannel_plots.root signal8 SChannel_plots.root signal8 SbarChannel_plots.root signal8 TWChannel_plots.root signal8 TbarWChannel_plots.root signal8 dimu_TTBar_plots.root signal8 muTau_TTBar_plots.root signal8 muE_TTBar_plots.root signal8 muHad_TTBar_plots.root signal8 others_TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_ctag-down.root  signal7 mue_ctag-down.root  signal7 muhad_ctag-down.root  signal7 mutau_ctag-down.root  signal7 others_ctag-down.root  signal7 sbar_ctag-down.root  signal7 s_ctag-down.root  signal7 tbar_ctag-down.root  signal7 t_ctag-down.root  signal7 tWbar_ctag-down.root  signal7 tW_ctag-down.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root > fit2.txt; cd -;

# cd JERDOWN;  ../FitCominedJES signal8 TChannel_plots.root signal8 TbarChannel_plots.root signal8 SChannel_plots.root signal8 SbarChannel_plots.root signal8 TWChannel_plots.root signal8 TbarWChannel_plots.root signal8 TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root > fit2.txt; cd -;

 cd JES-DOWN;  ../FitCominedJES signal8 TChannel_plots.root signal8 TbarChannel_plots.root signal8 SChannel_plots.root signal8 SbarChannel_plots.root signal8 TWChannel_plots.root signal8 TbarWChannel_plots.root signal8 TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_JES-down.root  signal7 mue_JES-down.root  signal7 muhad_JES-down.root  signal7 mutau_JES-down.root  signal7 others_JES-down.root  signal7 sbar_JES-down.root  signal7 s_JES-down.root  signal7 tbar_JES-down.root  signal7 t_JES-down.root  signal7 tWbar_JES-down.root  signal7 tW_JES-down.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root> fit2.txt; cd -;

 cd UNCMET-DOWN;  ../FitCominedJES signal8 TChannel_plots.root signal8 TbarChannel_plots.root signal8 SChannel_plots.root signal8 SbarChannel_plots.root signal8 TWChannel_plots.root signal8 TbarWChannel_plots.root signal8 TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_MET-down.root  signal7 mue_MET-down.root  signal7 muhad_MET-down.root  signal7 mutau_MET-down.root  signal7 others_MET-down.root  signal7 sbar_MET-down.root  signal7 s_MET-down.root  signal7 tbar_MET-down.root  signal7 t_MET-down.root  signal7 tWbar_MET-down.root  signal7 tW_MET-down.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root > fit2.txt; cd -;

cd  PU-DOWN;  ../FitComined signal8 TChannel_plots.root signal8 TbarChannel_plots.root signal8 SChannel_plots.root signal8 SbarChannel_plots.root signal8 TWChannel_plots.root signal8 TbarWChannel_plots.root signal8 dimu_TTBar_plots.root signal8 muTau_TTBar_plots.root signal8 muE_TTBar_plots.root signal8 muHad_TTBar_plots.root signal8 others_TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_pu-down.root  signal7 mue_pu-down.root  signal7 muhad_pu-down.root  signal7 mutau_pu-down.root  signal7 others_pu-down.root  signal7 sbar_pu-down.root  signal7 s_pu-down.root  signal7 tbar_pu-down.root  signal7 t_pu-down.root  signal7 tWbar_pu-down.root  signal7 tW_pu-down.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root > fit2.txt; cd -;

cd btag-UP;  ../FitComined signal8 TChannel_plots.root signal8 TbarChannel_plots.root signal8 SChannel_plots.root signal8 SbarChannel_plots.root signal8 TWChannel_plots.root signal8 TbarWChannel_plots.root signal8 dimu_TTBar_plots.root signal8 muTau_TTBar_plots.root signal8 muE_TTBar_plots.root signal8 muHad_TTBar_plots.root signal8 others_TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_btag-up.root  signal7 mue_btag-up.root  signal7 muhad_btag-up.root  signal7 mutau_btag-up.root  signal7 others_btag-up.root  signal7 sbar_btag-up.root  signal7 s_btag-up.root  signal7 tbar_btag-up.root  signal7 t_btag-up.root  signal7 tWbar_btag-up.root  signal7 tW_btag-up.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root > fit2.txt; cd -;

cd ctag-UP;  ../FitComined signal8 TChannel_plots.root signal8 TbarChannel_plots.root signal8 SChannel_plots.root signal8 SbarChannel_plots.root signal8 TWChannel_plots.root signal8 TbarWChannel_plots.root signal8 dimu_TTBar_plots.root signal8 muTau_TTBar_plots.root signal8 muE_TTBar_plots.root signal8 muHad_TTBar_plots.root signal8 others_TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_ctag-up.root  signal7 mue_ctag-up.root  signal7 muhad_ctag-up.root  signal7 mutau_ctag-up.root  signal7 others_ctag-up.root  signal7 sbar_ctag-up.root  signal7 s_ctag-up.root  signal7 tbar_ctag-up.root  signal7 t_ctag-up.root  signal7 tWbar_ctag-up.root  signal7 tW_ctag-up.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root > fit2.txt; cd -;

# cd JERUP;  ../FitCominedJES signal8 TChannel_plots.root signal8 TbarChannel_plots.root signal8 SChannel_plots.root signal8 SbarChannel_plots.root signal8 TWChannel_plots.root signal8 TbarWChannel_plots.root signal8 TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root > fit2.txt; cd -;

 cd JES-UP;  ../FitCominedJES signal8 TChannel_plots.root signal8 TbarChannel_plots.root signal8 SChannel_plots.root signal8 SbarChannel_plots.root signal8 TWChannel_plots.root signal8 TbarWChannel_plots.root signal8 TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_JES-up.root  signal7 mue_JES-up.root  signal7 muhad_JES-up.root  signal7 mutau_JES-up.root  signal7 others_JES-up.root  signal7 sbar_JES-up.root  signal7 s_JES-up.root  signal7 tbar_JES-up.root  signal7 t_JES-up.root  signal7 tWbar_JES-up.root  signal7 tW_JES-up.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root> fit2.txt; cd -;

cd UNCMET-UP;  ../FitCominedJES signal8 TChannel_plots.root signal8 TbarChannel_plots.root signal8 SChannel_plots.root signal8 SbarChannel_plots.root signal8 TWChannel_plots.root signal8 TbarWChannel_plots.root signal8 TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_MET-up.root  signal7 mue_MET-up.root  signal7 muhad_MET-up.root  signal7 mutau_MET-up.root  signal7 others_MET-up.root  signal7 sbar_MET-up.root  signal7 s_MET-up.root  signal7 tbar_MET-up.root  signal7 t_MET-up.root  signal7 tWbar_MET-up.root  signal7 tW_MET-up.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root> fit2.txt; cd -;

cd PU-UP;  ../FitComined signal8 TChannel_plots.root signal8 TbarChannel_plots.root signal8 SChannel_plots.root signal8 SbarChannel_plots.root signal8 TWChannel_plots.root signal8 TbarWChannel_plots.root signal8 dimu_TTBar_plots.root signal8 muTau_TTBar_plots.root signal8 muE_TTBar_plots.root signal8 muHad_TTBar_plots.root signal8 others_TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_pu-up.root  signal7 mue_pu-up.root  signal7 muhad_pu-up.root  signal7 mutau_pu-up.root  signal7 others_pu-up.root  signal7 sbar_pu-up.root  signal7 s_pu-up.root  signal7 tbar_pu-up.root  signal7 t_pu-up.root  signal7 tWbar_pu-up.root  signal7 tW_pu-up.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root > fit2.txt; cd -;
 
cd lumi-DOWN;  ../FitComined signal8 TChannel_plots.root signal8 TbarChannel_plots.root signal8 SChannel_plots.root signal8 SbarChannel_plots.root signal8 TWChannel_plots.root signal8 TbarWChannel_plots.root signal8 dimu_TTBar_plots.root signal8 muTau_TTBar_plots.root signal8 muE_TTBar_plots.root signal8 muHad_TTBar_plots.root signal8 others_TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_lumi-down.root  signal7 mue_lumi-down.root  signal7 muhad_lumi-down.root  signal7 mutau_lumi-down.root  signal7 rest_lumi-down.root  signal7 sbar_lumi-down.root  signal7 s_lumi-down.root  signal7 tbar_lumi-down.root  signal7 t_lumi-down.root  signal7 tWbar_lumi-down.root  signal7 tW_lumi-down.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root> fit2.txt; cd -;

cd lumi-UP;  ../FitComined signal8 TChannel_plots.root signal8 TbarChannel_plots.root signal8 SChannel_plots.root signal8 SbarChannel_plots.root signal8 TWChannel_plots.root signal8 TbarWChannel_plots.root signal8 dimu_TTBar_plots.root signal8 muTau_TTBar_plots.root signal8 muE_TTBar_plots.root signal8 muHad_TTBar_plots.root signal8 others_TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_lumi-up.root  signal7 mue_lumi-up.root  signal7 muhad_lumi-up.root  signal7 mutau_lumi-up.root  signal7 rest_lumi-up.root  signal7 sbar_lumi-up.root  signal7 s_lumi-up.root  signal7 tbar_lumi-up.root  signal7 t_lumi-up.root  signal7 tWbar_lumi-up.root  signal7 tW_lumi-up.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root> fit2.txt; cd -;

cd tt-DOWN;  ../FitComined signal8 TChannel_plots.root signal8 TbarChannel_plots.root signal8 SChannel_plots.root signal8 SbarChannel_plots.root signal8 TWChannel_plots.root signal8 TbarWChannel_plots.root signal8 dimu_TTBar_plots.root signal8 muTau_TTBar_plots.root signal8 muE_TTBar_plots.root signal8 muHad_TTBar_plots.root signal8 others_TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7  dimu_tt-down.root   signal7  mue_tt-down.root   signal7  muhad_tt-down.root   signal7  mutau_tt-down.root   signal7  rest_tt-down.root   signal7  sbar.root   signal7  s.root   signal7  tbar.root   signal7  t.root   signal7  tWbar.root   signal7  tW.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root > fit2.txt; cd -;

cd tt-UP;  ../FitComined signal8 TChannel_plots.root signal8 TbarChannel_plots.root signal8 SChannel_plots.root signal8 SbarChannel_plots.root signal8 TWChannel_plots.root signal8 TbarWChannel_plots.root signal8 dimu_TTBar_plots.root signal8 muTau_TTBar_plots.root signal8 muE_TTBar_plots.root signal8 muHad_TTBar_plots.root signal8 others_TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7  dimu_tt-up.root   signal7  mue_tt-up.root   signal7  muhad_tt-up.root   signal7  mutau_tt-up.root   signal7  rest_tt-up.root   signal7  sbar.root   signal7  s.root   signal7  tbar.root   signal7  t.root   signal7  tWbar.root   signal7  tW.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root > fit2.txt; cd -;

cd Scale-DOWN;  ../FitComined signal8 TChannel_plots.root signal8 TbarChannel_plots.root signal8 SChannel_plots.root signal8 SbarChannel_plots.root signal8 TWChannel_plots.root signal8 TbarWChannel_plots.root signal8 dimu_TTBar_plots.root signal8 muTau_TTBar_plots.root signal8 muE_TTBar_plots.root signal8 muHad_TTBar_plots.root signal8 others_TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_Scale-down.root  signal7 mue_Scale-down.root  signal7 muhad_Scale-down.root  signal7 mutau_Scale-down.root  signal7 others_Scale-down.root  signal7 sbar_Scale-down.root  signal7 s_Scale-down.root  signal7 tbar_Scale-down.root  signal7 t_Scale-down.root  signal7 tWbar_Scale-down.root  signal7 tW_Scale-down.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root > fit2.txt; cd -;

cd Scale-UP;  ../FitComined signal8 TChannel_plots.root signal8 TbarChannel_plots.root signal8 SChannel_plots.root signal8 SbarChannel_plots.root signal8 TWChannel_plots.root signal8 TbarWChannel_plots.root signal8 dimu_TTBar_plots.root signal8 muTau_TTBar_plots.root signal8 muE_TTBar_plots.root signal8 muHad_TTBar_plots.root signal8 others_TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_Scale-up.root  signal7 mue_Scale-up.root  signal7 muhad_Scale-up.root  signal7 mutau_Scale-up.root  signal7 others_Scale-up.root  signal7 sbar_Scale-up.root  signal7 s_Scale-up.root  signal7 tbar_Scale-up.root  signal7 t_Scale-up.root  signal7 tWbar_Scale-up.root  signal7 tW_Scale-up.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root > fit2.txt; cd -;

cd comphep;  ../FitComined signal8 Comphep.root signal8 SChannel_plots.root signal8 SbarChannel_plots.root signal8 TWChannel_plots.root signal8 TbarWChannel_plots.root signal8 TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7  dimu.root   signal7  mue.root   signal7  muhad.root   signal7  mutau.root   signal7  others.root   signal7  sbar.root   signal7  s.root   signal7  singletop_comphep_3.root   signal7  tWbar.root   signal7  tW.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root> fit2.txt; cd -;
