cd  PU-DOWN;  ../FitComined signal8 TChannel_plots.root signal8 TbarChannel_plots.root signal8 SChannel_plots.root signal8 SbarChannel_plots.root signal8 TWChannel_plots.root signal8 TbarWChannel_plots.root signal8 dimu_TTBar_plots.root signal8 muTau_TTBar_plots.root signal8 muE_TTBar_plots.root signal8 muHad_TTBar_plots.root signal8 others_TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 ../nominal/dimu.root  signal7 ../nominal/mue.root  signal7 ../nominal/muhad.root  signal7 ../nominal/mutau.root  signal7 ../nominal/others.root  signal7 ../nominal/sbar.root  signal7 ../nominal/s.root  signal7 ../nominal/tbar.root  signal7 ../nominal/t.root  signal7 ../nominal/tWbar.root  signal7 ../nominal/tW.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root > corfit8.txt; cd -;


cd  PU-DOWN;  ../FitComined signal8 ../nominal/TChannel_plots.root signal8 ../nominal/TbarChannel_plots.root signal8 ../nominal/SChannel_plots.root signal8 ../nominal/SbarChannel_plots.root signal8 ../nominal/TWChannel_plots.root signal8 ../nominal/TbarWChannel_plots.root signal8 ../nominal/dimu_TTBar_plots.root signal8 ../nominal/muTau_TTBar_plots.root signal8 ../nominal/muE_TTBar_plots.root signal8 ../nominal/muHad_TTBar_plots.root signal8 ../nominal/others_TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_pu-down.root  signal7 mue_pu-down.root  signal7 muhad_pu-down.root  signal7 mutau_pu-down.root  signal7 others_pu-down.root  signal7 sbar_pu-down.root  signal7 s_pu-down.root  signal7 tbar_pu-down.root  signal7 t_pu-down.root  signal7 tWbar_pu-down.root  signal7 tW_pu-down.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root > corfit7.txt; cd -;


cd PU-UP;  ../FitComined signal8 ../nominal/TChannel_plots.root signal8 ../nominal/TbarChannel_plots.root signal8 ../nominal/SChannel_plots.root signal8 ../nominal/SbarChannel_plots.root signal8 ../nominal/TWChannel_plots.root signal8 ../nominal/TbarWChannel_plots.root signal8 ../nominal/dimu_TTBar_plots.root signal8 ../nominal/muTau_TTBar_plots.root signal8 ../nominal/muE_TTBar_plots.root signal8 ../nominal/muHad_TTBar_plots.root signal8 ../nominal/others_TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 dimu_pu-up.root  signal7 mue_pu-up.root  signal7 muhad_pu-up.root  signal7 mutau_pu-up.root  signal7 others_pu-up.root  signal7 sbar_pu-up.root  signal7 s_pu-up.root  signal7 tbar_pu-up.root  signal7 t_pu-up.root  signal7 tWbar_pu-up.root  signal7 tW_pu-up.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root > corfit7.txt; cd -;


cd PU-UP;  ../FitComined signal8 TChannel_plots.root signal8 TbarChannel_plots.root signal8 SChannel_plots.root signal8 SbarChannel_plots.root signal8 TWChannel_plots.root signal8 TbarWChannel_plots.root signal8 dimu_TTBar_plots.root signal8 muTau_TTBar_plots.root signal8 muE_TTBar_plots.root signal8 muHad_TTBar_plots.root signal8 others_TTBar_plots.root bkg8 bkg.root data8 ../Data_plots.root signal7 ../nominal/dimu.root  signal7 ../nominal/mue.root  signal7 ../nominal/muhad.root  signal7 ../nominal/mutau.root  signal7 ../nominal/others.root  signal7 ../nominal/sbar.root  signal7 ../nominal/s.root  signal7 ../nominal/tbar.root  signal7 ../nominal/t.root  signal7 ../nominal/tWbar.root  signal7 ../nominal/tW.root  bkg7 ../bkg_noW.root   wtemplate7  ../BOrderedBTemplateIso.root data7 ../Summer11_paper_plots.root > corfit8.txt; cd -;
